language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clear build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - llsb156@gmail.com
