language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-on-aws-with-travisCI *
  - mkdir -p deploy
  - mv springboot-on-aws-with-travisCI.zip deploy/springboot-on-aws-with-travisCI.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-on-aws-with-travisci
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-on-aws-with-travisci
    key: springboot-on-aws-with-travisCI.zip
    bundle_type: zip
    application: springboot_on_aws_with_travisCI
    deployment-group: springboot_on_aws_with_travisCI_group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - llsb156@gmail.com


